name: test
on:
  schedule:
    - cron: '18 12 * * 2'
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      # Set fetch-depth: 0 to fetch commit history and tags for use in version calculation
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build and test
        uses: hypertrace/github-actions/gradle@main
        with:
          args: build jacocoTestReport

      - name: copy test reports
        uses: hypertrace/github-actions/gradle@main
        if: failure()
        with:
          args: copyAllReports --output-dir=/tmp/test-reports

      - name: Archive test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: /tmp/test-reports
        if: failure()

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (success() || failure()) && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository)
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: ./**/build/test-results/**/*.xml
  dependency-check:
    runs-on: ubuntu-24.04
    steps:
      - name: Dependency Check
        uses: hypertrace/github-actions/dependency-check@main
        with:
          nvd-api-key: ${{ secrets.NVD_API_KEY }}
